version: "3.9"
#OVERRIDE ENV WITH SECRETS AT DEPLOY STAGE
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    deploy:
      resources:
        limits:
          cpus: '0.75'
    volumes:
      - './backend/src:/app'
    working_dir: /app
    ports:
      - '8008:8008'

